language: java
env:
  global:
    secure: D2krX9UB8MZEezuDgQb59c4QiyhJcZUw7yw7CdcQWabxG24DibhOp1fuyVbTMa/9t7lM6o5iKDN5J2v07NnRQ3fujvB6JoeljaQVjQ4Int+Y5XPd6pN3BrqZVRXL7EHw3ogM98JDJtrt3E3DssJS/7w0chhHgjrO5JNzRCkIN+GcI0YPwhFNmLv4zO2KeYUuH1yC0OBe7SQEBP4z/F/9IjojRVq08eJsyTJOqOwczjUbelwXm4gW3gKQuAPvFYdgmdggv8piKZX/IG4V6tT2xSEjj2GBUOQgxuHHILZVZw4n7wguNj0beJMgEJc1NtoU4ox/F8iw7jHSNGp6R004tDvvdE8EQpewwNkXXWvQn1eNYBfZqQl6uGCYvotB/hH6b+iwCQyIv4kVTLeOYpwu8J78oh6YsHJhcHWWLUD5yWrNQDe/DKKDlZVykd3jDWZBv0aeqjEV8SWN+DCKjkTtFgQxnxRz3royWSvYWWAiCTh4pPy9tD3p1q0i9ccmEEPeR4gsmaBfVccSnzZpkR8PNmm/cMxc5mF6Lxi/c9rAbpK1Mx6RDvEh7+YRl0w0DhXWX+YoZtjf2TjTdSFh/KqukzlyLursDQw9JkNdz2vlXdwmKRtje4iyC1+NGHggUumrScTRB1yTknVfbeQOLfw5KZ1azo7/nAcNAgWxeDc9w/c=
jdk:
- oraclejdk8
services:
- mongodb
- rabbitmq
sudo: required
branches:
  only:
  - staging
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- chmod a+x merge_script.sh
- BRANCHES_TO_MERGE_REGEX='staging' BRANCH_TO_MERGE_INTO=develop GITHUB_REPO=symbiote-h2020/CloudAuthenticationAuthorizationManager
  ./merge_script.sh
- bash <(curl -s https://codecov.io/bash)
