language: java
env:
  global:
  - GITHUB_REPO=symbiote-h2020/CoreAuthenticationAuthorizationManager
  - secure: rip+g8jhX+RzehwW+tF0gDcrjJ1tD2ehtMdHutojTKgw+d24U3p+Rcm1qwC2vVQtQNbgz7tXJo1Rbiz0MGmpZTbKPuPHYSdMFpTSNAN/FxQalM+mcyy3qw6Q+veEMK2yB89jd4+VLbyMJ/40PcPdORDOA3ljvZ/u3h1s8yaftVuXLiJkoiL3yB5BudH6JFjlo4ar01nbCZzMMSBU/Fy0cebgPawDGsyyBW0LP4x+hkEixgmJW3fYhnpM10EnYzmtwCUIbEPrrOmCrlC/qN84i0WRW65aGQrOfmkBgN2zHpaM/6DKQ5mYBUuKPGyeut8dJDU1R/RpMy54HHqotsYFYvj/5DWlxET1nUuMXfUccNsFN7+6ij7Aqa+9H3lxZAKBrmBTekYPAOkb2Eyvc6rs164C9KyBVEvKGBFOgaZx0GQGk5IFqETXKcr85QelFdHBV11eKQwghCrLK1yYMvt3GErLTv3M420fDotoICsnUE/OT08zZz1Y21t0r1r+HskX/SFQ5uLVJPY7oslL+0Kxz2Q4kbTmYkwUdPVc7TxbqQ7WnzzZqeYizWtazVcKzUWAUOm5EGov2RXJJRa9Ni9+39rsPFegbiR6UbgPoPrqTPTSYG4d/jEnGrLU9yVbjkGFq5aSwz9Gn1i44e3vrkEnNbpHec3WF/wlrhaCwnSMYn0=
jdk:
- oraclejdk8
services:
- mongodb
- rabbitmq
sudo: required
branches:
  only:
  - staging
install: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_script:
- chmod a+x merge_script.sh
- "./merge_script.sh"
after_success:
- chmod a+x pushing_script.sh
- "./pushing_script.sh"
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: always
