language: java
env:
  global:
  - GITHUB_REPO=symbiote-h2020/AuthenticationAuthorizationManager
  - secure: TO_BE_FIXED
jdk:
- oraclejdk8
services:
- mongodb
- rabbitmq
sudo: required
branches:
  only:
  - staging
install: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_script:
- chmod a+x merge_script.sh
- "./merge_script.sh"
after_success:
- chmod a+x pushing_script.sh
- "./pushing_script.sh"
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: always
